[redis]
chunk_size = 10
blocktime_millis = 1000
consumer_group = "log-ingestor"
consumer_id = "log-ingestor"

[redis.url]
url = "redis://127.0.0.1"
port = 6379

[loki]
api_key = "RjhrMWY1Z0J4ZjV0T0NJQmIzdjU6ZjVURGdmWmVCM3I3ckd2ZmFLUXl6UQ=="
chunk_size = 100
index = "logstash-bec_test123"
beamline_name = "x99xa"

[loki.url]
url = "http://localhost"
port = 9200
