[redis]
chunk_size = 10
blocktime_millis = 1000
consumer_group = "log-ingestor"
consumer_id = "log-ingestor"

[redis.url]
url = "redis://127.0.0.1"
port = 6379

[loki]
url = "http://localhost"
auth = { username = "test-loki", password = "test-loki-password" }
chunk_size = 100
beamline_name = "x99xa"

