[redis]
chunk_size = 10
blocktime_millis = 1000
consumer_group = "log-ingestor"
consumer_id = "log-ingestor"

[redis.url]
url = "redis://127.0.0.1"
port = 6379

[loki]
url = "http://localhost"
auth = { username = "test-loki", password = "test-loki-password" }
chunk_size = 100
beamline_name = "x99xa"

[metrics]
user_config_path = "./test/test_metrics_config.toml"
url = "http://localhost"
auth = { username = "test-mimir", password = "test-mimir-password" }

[metrics.intervals]
new_metric = { Secondly = 53 }
cpu_usage_percent = { Secondly = 15 }
ram_usage_bytes = { Secondly = 30 }

[metrics.dynamic]
dynamic_metric = { read_type = { Poll = { Secondly = 15 } }, key = "/user/dynamicmetrics/1", dtype = "Float" }
dynamic_metric_2 = { read_type = "PubSub", key = "/user/dynamicmetrics/2", dtype = "String" }
